# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoProject
  pod 'GoogleMaps'
  

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

end
